---
- hosts: all
  become: true

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Upgrade all packages on servers
      apt: 
        name: "*"
        state: latest

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Create the build directory
      file:
        path: /root/nginx-custom
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: Copy Dockerfile
      copy:
        src: ./nginx/Dockerfile
        dest: /root/nginx-custom/Dockerfile
        owner: root
        group: root
        mode: '0644'
    - name: Copy index.html
      copy:
        src: ./nginx/index.html
        dest: /root/nginx-custom/index.html
        owner: root
        group: root
        mode: '0644'
    - name: Copy assets
      copy:
        src: ./nginx/assets
        dest: /root/nginx-custom/assets
        owner: root
        group: root
        mode: '0644'
    - name: Copy default.conf
      copy:
        src: ./nginx/default.conf
        dest: /root/nginx-custom/default.conf
        owner: root
        group: root
        mode: '0644'
    - name: Build the Nginx Docker image
      command: docker build -t nginx-custom:v1.0 /root/nginx-custom
    - name: Deploy Nginx Docker container
      docker_container:
        image: nginx-custom:v1.0
        name: nginx
        state: started
        auto_remove: true
        ports:
          - "80:80"